# Generated by Django 5.0.2 on 2024-03-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storiesmodel',
            name='is_img',
            field=models.BooleanField(default=False),
        ),
    ]
