# Generated by Django 5.0.2 on 2024-03-13 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_messagemodel_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='men', to=settings.AUTH_USER_MODEL)),
                ('show_him', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korinedigon_odam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
