# Generated by Django 5.0.2 on 2024-03-25 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='last_active',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
